version: 2
models:
  - name: customers
    description: '{{ doc("table_customers") }}'
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
  - name: orders
    description: An orders table with amount added for each order.
    columns:
      - name: order_id
        tests:
          - not_null
        name: customer_id
        tests:
          - not_null
  - name: jinja_payments
    description: A pivoted payments table
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
 